name: Build Cheat Engine

on:
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: windows-2022

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Install Lazarus and Free Pascal
      uses: gcarreno/setup-lazarus@v3
      with:
        lazarus-version: 'stable'

    - name: Build Cheat Engine Main App
      run: |
        cd "Cheat Engine"
        # --userdir parametresi ile Lazarus'un kurulu olduğu dizindeki tüm bileşenleri (lazutils dahil) zorunlu olarak projeye dahil ediyoruz
        lazbuild --userdir="C:\Users\runneradmin\AppData\Local\lazarus" --primary-config-path=. cheatengine.lpi --build-mode=Release

    - name: Upload Compiled Binary
      uses: actions/upload-artifact@v4
      with:
        name: Compiled-Cheat-Engine
        path: |
          Cheat Engine/bin/
